# tasks file for ssh-server
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: 3600
  with_items: ssh_server_dependencies
  tags: [configuration, ssh-server, ssh-server-dependencies]

- name: install
  apt:
    name: "{{ item }}"
    state: latest
  with_items: ssh_server_install
  tags: [configuration, ssh-server, ssh-server-install]
