# tasks file
---
- name: get (current) version  # noqa risky-shell-pipe
  ansible.builtin.shell: >
    dpkg-query -W -f='${Version}' openssh-server | awk -F':' '{print $2}' | awk -F'p' '{print $1}'
  register: _get_current_version
  changed_when: false
  failed_when: false
  tags:
    - configuration
    - ssh-server
    - ssh-server-version
    - ssh-server-version-get

- name: set (current) version
  ansible.builtin.set_fact:
    ssh_server_version: "{{ _get_current_version.stdout | regex_search('^([0-9]+\\.[0-9]+\\.?[0-9]*)$') }}"
  changed_when: false
  check_mode: false
  tags:
    - configuration
    - ssh-server
    - ssh-server-version
    - ssh-server-version-set

- name: install dependencies
  ansible.builtin.apt:
    name: "{{ ssh_server_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - ssh-server
    - ssh-server-dependencies

- name: install
  ansible.builtin.apt:
    name: "{{ ssh_server_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - configuration
    - ssh-server
    - ssh-server-install

- name: check host keys
  ansible.builtin.command: >
    ssh-keygen -A
  args:
    creates: "{{ item }}"
  register: _check_host_keys
  changed_when: "'generating new host keys' in _check_host_keys.stdout"
  with_items: "{{ ssh_server_host_keys }}"
  when: item | length
  tags:
    - configuration
    - ssh-server
    - ssh-server-check-host-keys

- name: stat directories
  ansible.builtin.stat:
    path: "{{ item }}/"
  register: _stat_directories
  with_items:
    - "{{ ssh_server_config_file | dirname }}"
    - "{{ ssh_server_runtime_directory }}"
  tags:
    - configuration
    - ssh-server
    - ssh-server-configure
    - ssh-server-configure-directories
    - ssh-server-configure-directories-stat

- name: create directories
  ansible.builtin.file:
    path: "{{ item.item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: "{{ _stat_directories.results }}"
  when:
    - item.stat is defined
    - not item.stat.exists
  tags:
    - configuration
    - ssh-server
    - ssh-server-configure
    - ssh-server-configure-directories
    - ssh-server-configure-directories-create

- name: update configuration file
  ansible.builtin.template:
    src: "{{ ssh_server_config_file.lstrip('/') }}.j2"
    dest: "{{ ssh_server_config_file }}"
    owner: root
    group: root
    mode: 0644
    validate: 'sshd -T -f %s'
  notify: restart ssh
  tags:
    - configuration
    - ssh-server
    - ssh-server-configure
    - ssh-server-configure-file

- name: start and enable service
  ansible.builtin.service:
    name: ssh
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - ssh-server
    - ssh-server-start-enable-service
