# tasks file for ssh-server
---
- name: install dependencies
  apt:
    name: "{{ ssh_server_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - ssh-server
    - ssh-server-dependencies

- name: install
  apt:
    name: "{{ ssh_server_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - configuration
    - ssh-server
    - ssh-server-install

- name: check host keys
  command: ssh-keygen -A
  args:
    creates: "{{ ssh_server_host_keys }}"
  register: check_host_keys
  changed_when: "'generating new host keys' in check_host_keys.stdout"
  when: item != '' and (ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('12.04', '>=') or ansible_distribution == 'Debian' and ansible_distribution_version | version_compare('7.0', '>='))
  tags:
    - configuration
    - ssh-server
    - ssh-server-check-host-keys

- name: update configuration file
  template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    validate: 'sshd -T -f %s'
  notify: restart ssh
  tags:
    - configuration
    - ssh-server
    - ssh-server-configuration

- name: start and enable service
  service:
    name: ssh
    state: started
    enabled: true
  tags:
    - configuration
    - ssh-server
    - ssh-server-start-enable-service
