# tasks file for ssh-server
---
- include: install.yml

- name: start and enable service
  service:
    name: ssh
    state: started
    enabled: yes
  tags: [configuration, ssh-server, ssh-server-start-enable-service]
