# tasks file for ssh-server
---
- name: install package
  apt:
    name: openssh-server
    state: latest
    update_cache: true
    cache_valid_time: 3600
  tags: [configuration, ssh-server, ssh-server-install]

- name: start and enable service
  service:
    name: ssh
    state: started
    enabled: yes
  tags: [configuration, ssh-server, ssh-server-start-enable-service]
